# Generated by Django 4.0.2 on 2022-06-04 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('ingredients', models.CharField(blank=True, max_length=500, verbose_name='Ингридиенты')),
                ('about', models.CharField(max_length=500, verbose_name='Описание')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Товары',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Подпись')),
                ('price', models.IntegerField(null=True, verbose_name='Цена')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Цены',
                'verbose_name_plural': 'Цены',
                'ordering': ['pk'],
            },
        ),
    ]
