# Generated by Django 4.0.2 on 2022-05-23 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='price_id',
        ),
    ]
