# Generated by Django 4.0.2 on 2022-05-24 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('pizza', '0002_remove_price_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.cartitem'),
            preserve_default=False,
        ),
    ]
