# Generated by Django 4.0.2 on 2022-05-24 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_price_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='cart',
        ),
    ]
